# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 21:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastosmensuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mes', models.CharField(max_length=100)),
                ('PrecioPiso', models.IntegerField(null=True)),
                ('PrecioGas', models.IntegerField(null=True)),
                ('PrecioLuz', models.IntegerField(null=True)),
                ('PrecioInternet', models.IntegerField(null=True)),
                ('PrecioTotal', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listacompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DineroPersona', models.IntegerField(null=True)),
                ('Productos', models.TextField(max_length=700, null=True)),
                ('fechalista', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Texto', models.TextField(max_length=500, null=True)),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Precio', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Limpieza', models.CharField(max_length=100)),
                ('Basura', models.CharField(max_length=100)),
                ('Extra', models.CharField(max_length=100)),
                ('Semana', models.CharField(max_length=100)),
                ('MesTarea', models.CharField(max_length=100)),
                ('Pisos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piso.Piso')),
            ],
        ),
        migrations.AddField(
            model_name='notas',
            name='Pisos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piso.Piso'),
        ),
        migrations.AddField(
            model_name='listacompra',
            name='Pisos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piso.Piso'),
        ),
        migrations.AddField(
            model_name='gastosmensuales',
            name='Pisos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piso.Piso'),
        ),
    ]
